<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Electronics
            [
                'category_id' => 1,
                'name' => 'Wireless Mouse',
                'slug' => 'wireless-mouse',
                'sku' => 'ELEC-001',
                'description' => 'Ergonomic wireless mouse with precision tracking',
                'price' => 150000,
                'stock' => 50,
                'stock_control' => true,
                'images' => ['products/wireless-mouse.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Mechanical Keyboard',
                'slug' => 'mechanical-keyboard',
                'sku' => 'ELEC-002',
                'description' => 'RGB mechanical keyboard with blue switches',
                'price' => 750000,
                'stock' => 30,
                'stock_control' => true,
                'images' => ['products/keyboard.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'USB-C Hub',
                'slug' => 'usbc-hub',
                'sku' => 'ELEC-003',
                'description' => '7-in-1 USB-C hub with HDMI and Ethernet',
                'price' => 350000,
                'stock' => 25,
                'stock_control' => true,
                'images' => ['products/usb-hub.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Webcam HD',
                'slug' => 'webcam-hd',
                'sku' => 'ELEC-004',
                'description' => '1080p webcam for video conferencing',
                'price' => 500000,
                'stock' => 15,
                'stock_control' => true,
                'images' => ['products/webcam.jpg'],
                'is_active' => true,
            ],

            // Fashion
            [
                'category_id' => 2,
                'name' => 'Cotton T-Shirt',
                'slug' => 'cotton-tshirt',
                'sku' => 'FASH-001',
                'description' => 'Premium cotton t-shirt, available in multiple colors',
                'price' => 120000,
                'stock' => 100,
                'stock_control' => true,
                'images' => ['products/tshirt.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Denim Jeans',
                'slug' => 'denim-jeans',
                'sku' => 'FASH-002',
                'description' => 'Slim fit denim jeans with stretch fabric',
                'price' => 350000,
                'stock' => 60,
                'stock_control' => true,
                'images' => ['products/jeans.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Sneakers',
                'slug' => 'sneakers',
                'sku' => 'FASH-003',
                'description' => 'Comfortable casual sneakers for daily wear',
                'price' => 450000,
                'stock' => 40,
                'stock_control' => true,
                'images' => ['products/sneakers.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Backpack',
                'slug' => 'backpack',
                'sku' => 'FASH-004',
                'description' => 'Laptop backpack with water-resistant material',
                'price' => 250000,
                'stock' => 35,
                'stock_control' => true,
                'images' => ['products/backpack.jpg'],
                'is_active' => true,
            ],

            // Books
            [
                'category_id' => 3,
                'name' => 'Laravel Best Practices',
                'slug' => 'laravel-best-practices',
                'sku' => 'BOOK-001',
                'description' => 'Comprehensive guide to Laravel development',
                'price' => 200000,
                'stock' => 20,
                'stock_control' => true,
                'images' => ['products/book-laravel.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Clean Code',
                'slug' => 'clean-code',
                'sku' => 'BOOK-002',
                'description' => 'Writing maintainable and readable code',
                'price' => 180000,
                'stock' => 15,
                'stock_control' => true,
                'images' => ['products/book-clean-code.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Design Patterns',
                'slug' => 'design-patterns',
                'sku' => 'BOOK-003',
                'description' => 'Essential design patterns in software development',
                'price' => 220000,
                'stock' => 12,
                'stock_control' => true,
                'images' => ['products/book-patterns.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Database Design',
                'slug' => 'database-design',
                'sku' => 'BOOK-004',
                'description' => 'Database design principles and optimization',
                'price' => 190000,
                'stock' => 18,
                'stock_control' => true,
                'images' => ['products/book-database.jpg'],
                'is_active' => true,
            ],

            // Food & Beverage
            [
                'category_id' => 4,
                'name' => 'Premium Coffee Beans',
                'slug' => 'premium-coffee-beans',
                'sku' => 'FOOD-001',
                'description' => 'Arabica coffee beans from local farmers',
                'price' => 85000,
                'stock' => 50,
                'stock_control' => true,
                'images' => ['products/coffee.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Organic Tea Set',
                'slug' => 'organic-tea-set',
                'sku' => 'FOOD-002',
                'description' => 'Collection of organic herbal teas',
                'price' => 120000,
                'stock' => 30,
                'stock_control' => true,
                'images' => ['products/tea-set.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Dark Chocolate Bar',
                'slug' => 'dark-chocolate-bar',
                'sku' => 'FOOD-003',
                'description' => '70% dark chocolate with sea salt',
                'price' => 45000,
                'stock' => 100,
                'stock_control' => true,
                'images' => ['products/chocolate.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Honey Jar',
                'slug' => 'honey-jar',
                'sku' => 'FOOD-004',
                'description' => 'Pure raw honey from local beekeepers',
                'price' => 95000,
                'stock' => 40,
                'stock_control' => true,
                'images' => ['products/honey.jpg'],
                'is_active' => true,
            ],

            // Home & Living
            [
                'category_id' => 5,
                'name' => 'Desk Lamp',
                'slug' => 'desk-lamp',
                'sku' => 'HOME-001',
                'description' => 'LED desk lamp with adjustable brightness',
                'price' => 180000,
                'stock' => 25,
                'stock_control' => true,
                'images' => ['products/desk-lamp.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Wall Clock',
                'slug' => 'wall-clock',
                'sku' => 'HOME-002',
                'description' => 'Modern minimalist wall clock',
                'price' => 150000,
                'stock' => 20,
                'stock_control' => true,
                'images' => ['products/wall-clock.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Cushion Set',
                'slug' => 'cushion-set',
                'sku' => 'HOME-003',
                'description' => 'Set of 4 decorative cushions',
                'price' => 220000,
                'stock' => 30,
                'stock_control' => true,
                'images' => ['products/cushions.jpg'],
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Storage Box',
                'slug' => 'storage-box',
                'sku' => 'HOME-004',
                'description' => 'Multipurpose fabric storage box',
                'price' => 75000,
                'stock' => 45,
                'stock_control' => true,
                'images' => ['products/storage-box.jpg'],
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
